kind: ConfigMap
apiVersion: v1
metadata:
  name: test-redis-conf
  namespace: test
data:
    redis.conf: |
      daemonize no
      pidfile /var/run/redis.pid
      port 6379
      bind 0.0.0.0
      timeout 0
      loglevel notice
      databases 16
      save 900 1
      save 300 10
      save 60 10000
      rdbcompression yes
      dbfilename dump.rdb
      dir /data
      maxclients 128
      requirepass dxheIicL1M
      appendonly yes
      appendfilename appendonly.aof
      appendfsync everysec
      no-appendfsync-on-rewrite no
      auto-aof-rewrite-percentage 100
      auto-aof-rewrite-min-size 256mb
      slowlog-log-slower-than 1000000
      slowlog-max-len 128
      client-output-buffer-limit normal 0 0 0
      hz 10
      aof-rewrite-incremental-fsync yes