apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-redis
  namespace: test
  labels:
    app: test-redis
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 1
  selector:
    matchLabels:
      app: test-redis
  serviceName: test-redis-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: test-redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: test-redis
        image: redis
        imagePullPolicy: IfNotPresent
        command:
        - sh
        args:
        - -c
        - redis-server
        - /opt/redis.conf
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
        ports:
        - containerPort: 6379
          protocol: TCP
          name: test-redis
        volumeMounts:
        - name: test-redis-conf
          mountPath: /opt
        - name: test-redis-data
          mountPath: /data
      restartPolicy: Always
      volumes:
      - name: test-redis-data
        persistentVolumeClaim:
          claimName: pvc-test-redis-5gb-ebs-01
      - name: test-redis-conf
        configMap:
          name: test-redis-conf