apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test-redis-5gb-ebs-01-vol-029b74bf3ed0e5f5b
  labels:
    app: test-redis
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://ap-northeast-2c/vol-029b74bf3ed0e5f5b
  capacity:
    storage: 5Gi
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - ap-northeast-2c
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - ap-northeast-2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test-redis-5gb-ebs-01
  namespace: test
  labels:
    app: test-redis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: pv-test-redis-5gb-ebs-01-vol-029b74bf3ed0e5f5b